/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sever;

import QLDV.QLDVForm;
import QLHV.FormQLHV;
import QLMT.FormQLMT;
import QLNV.FormQLNV;
import QLTK.QLTKForm;
import ThongKe.ThongKe;

/**
 *
 * @author Dang Do
 */
public class GiaoDienQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienQuanLy
     */
    public GiaoDienQuanLy() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(189,231,253));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        QLMT = new javax.swing.JButton();
        QLTK = new javax.swing.JButton();
        QLHV = new javax.swing.JButton();
        QLDV = new javax.swing.JButton();
        QLNV = new javax.swing.JButton();
        TKDT = new javax.swing.JButton();
        DangXuat = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        txtTenDN = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("PHÒNG MÁY DVD");

        QLMT.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        QLMT.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\quanlymaytram.png")); // NOI18N
        QLMT.setText("QUẢN LÝ MÁY TRẠM");
        QLMT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        QLMT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        QLMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLMTActionPerformed(evt);
            }
        });

        QLTK.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        QLTK.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\quanlytaikhoan.png")); // NOI18N
        QLTK.setText("QUẢN LÝ TÀI KHOẢN");
        QLTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        QLTK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        QLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLTKActionPerformed(evt);
            }
        });

        QLHV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        QLHV.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\quanlyhoivien.png")); // NOI18N
        QLHV.setText("QUẢN LÝ HỘI VIÊN");
        QLHV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        QLHV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        QLHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLHVActionPerformed(evt);
            }
        });

        QLDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        QLDV.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\quanlydichvu.png")); // NOI18N
        QLDV.setText("QUẢN LÝ DỊCH VỤ");
        QLDV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        QLDV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        QLDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLDVActionPerformed(evt);
            }
        });

        QLNV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        QLNV.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\quanlynhanvien.png")); // NOI18N
        QLNV.setText("QUẢN LÝ NHÂN VIÊN");
        QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        QLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLNVActionPerformed(evt);
            }
        });

        TKDT.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TKDT.setIcon(new javax.swing.ImageIcon("C:\\Java\\ProjectQuanNet\\Images_Pro\\nhatkygiaodich (2).png")); // NOI18N
        TKDT.setText("THỐNG KÊ DOANH THU");
        TKDT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TKDT.setMaximumSize(new java.awt.Dimension(147, 105));
        TKDT.setMinimumSize(new java.awt.Dimension(147, 105));
        TKDT.setPreferredSize(new java.awt.Dimension(147, 105));
        TKDT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TKDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKDTActionPerformed(evt);
            }
        });

        DangXuat.setText("ĐĂNG XUẤT");
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });

        Thoat.setText("THOÁT");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        txtTenDN.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTenDN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("THÔNG TIN PHẦN MỀM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QLMT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(TKDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QLHV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLMT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLHV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TKDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QLMT.getAccessibleContext().setAccessibleName("100");
        QLTK.getAccessibleContext().setAccessibleName("100");
        QLHV.getAccessibleContext().setAccessibleName("100");
        QLDV.getAccessibleContext().setAccessibleName("100");
        QLNV.getAccessibleContext().setAccessibleName("100");
        TKDT.getAccessibleContext().setAccessibleName("100");
        DangXuat.getAccessibleContext().setAccessibleName("90");
        Thoat.getAccessibleContext().setAccessibleName("90");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLMTActionPerformed
        
        FormQLMT f1 = new FormQLMT();
        f1.setVisible(true);
    }//GEN-LAST:event_QLMTActionPerformed

    private void QLHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLHVActionPerformed

        FormQLHV f1 = new FormQLHV();
        f1.setVisible(true);
    }//GEN-LAST:event_QLHVActionPerformed

    private void QLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLTKActionPerformed
        
        QLTKForm f1 = new QLTKForm();
        f1.setVisible(true);
    }//GEN-LAST:event_QLTKActionPerformed

    private void QLDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLDVActionPerformed
       
        QLDVForm f1 = new QLDVForm();
        f1.setVisible(true);
    }//GEN-LAST:event_QLDVActionPerformed

    private void QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLNVActionPerformed
        
        FormQLNV f1 = new FormQLNV();
        f1.setVisible(true);
    }//GEN-LAST:event_QLNVActionPerformed

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed
        dispose();
        LoginSever lg = new LoginSever();
        lg.setVisible(true);
    }//GEN-LAST:event_DangXuatActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        dispose();
    }//GEN-LAST:event_ThoatActionPerformed

    private void TKDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKDTActionPerformed
       
        ThongKe tk = new ThongKe();
        tk.setVisible(true);
    }//GEN-LAST:event_TKDTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ThongTin tt = new ThongTin();
        tt.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DangXuat;
    public static javax.swing.JButton QLDV;
    private javax.swing.JButton QLHV;
    private javax.swing.JButton QLMT;
    public static javax.swing.JButton QLNV;
    private javax.swing.JButton QLTK;
    private javax.swing.JButton TKDT;
    private javax.swing.JButton Thoat;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel txtTenDN;
    // End of variables declaration//GEN-END:variables
}
